module.exports = class Data1754071385033 {
    name = 'Data1754071385033'

    async up(db) {
        await db.query(`CREATE TABLE "pool_factory" ("id" character varying NOT NULL, "address" text NOT NULL, "chain_id" integer NOT NULL, "pool_count" integer NOT NULL, "owner_id" character varying NOT NULL, "created_at_block_number" integer NOT NULL, "updated_at_block_number" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_c25b5c35c9b63c7ab8e29f87aa7" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_37d0c98b2aee82e865df4ca6ed" ON "pool_factory" ("owner_id") `)
        await db.query(`CREATE TABLE "extension_registry" ("id" character varying NOT NULL, "address" text NOT NULL, "chain_id" integer NOT NULL, "extension_count" integer NOT NULL, "owner_id" character varying NOT NULL, "created_at_block_number" integer NOT NULL, "updated_at_block_number" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_f5394f62a41c12489d2930fb43a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_23035bc1fa4a5b221389e13d92" ON "extension_registry" ("owner_id") `)
        await db.query(`CREATE TABLE "extension" ("id" character varying NOT NULL, "address" text NOT NULL, "chain_id" integer NOT NULL, "extension_registry_id" character varying NOT NULL, "extension_id" text NOT NULL, "extension_type" character varying(8) NOT NULL, "permissions" text array, "data" jsonb, "name" text NOT NULL, "description" text NOT NULL, "created_at_block_number" integer NOT NULL, "updated_at_block_number" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_e9e7da4f1cfc826aba870c20589" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_57ccff353e966f42ce075c9840" ON "extension" ("extension_registry_id") `)
        await db.query(`CREATE TABLE "claim" ("id" character varying NOT NULL, "value" numeric NOT NULL, "parent_id" character varying, "pool_id" character varying NOT NULL, "recipient_id" character varying, "state_id" character varying NOT NULL, "strategy_id" character varying NOT NULL, "created_at_block_number" integer NOT NULL, "updated_at_block_number" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_466b305cc2e591047fa1ce58f81" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_1be67f374e054c831d78dc0488" ON "claim" ("parent_id") `)
        await db.query(`CREATE INDEX "IDX_4fa8a234dee5be6b41e76819d2" ON "claim" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_fbd012a2329b07b1687c321385" ON "claim" ("recipient_id") `)
        await db.query(`CREATE INDEX "IDX_964f2b34087ff0363398bfcba6" ON "claim" ("state_id") `)
        await db.query(`CREATE INDEX "IDX_c9c7ae261e98272b62051f3b1b" ON "claim" ("strategy_id") `)
        await db.query(`CREATE TABLE "token" ("id" character varying NOT NULL, "address" text NOT NULL, "chain_id" integer NOT NULL, "symbol" text NOT NULL, "name" text NOT NULL, "decimals" integer NOT NULL, "logo" text, "thumbnail" text, "validated" integer, "possible_spam" boolean, "created_at_block_number" integer NOT NULL, "updated_at_block_number" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_82fae97f905930df5d62a702fc9" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "pool_day_balance" ("id" character varying NOT NULL, "date" TIMESTAMP WITH TIME ZONE NOT NULL, "pool_id" character varying NOT NULL, "token_id" character varying NOT NULL, "amount" numeric NOT NULL, "created_at_block_number" integer NOT NULL, "updated_at_block_number" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_816bb792bbc9733b342715f9d01" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_652bc46dc1f15a99ad2682d0da" ON "pool_day_balance" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_7e08123ddf2be25b7888311d8a" ON "pool_day_balance" ("token_id") `)
        await db.query(`CREATE TABLE "pool_hour_balance" ("id" character varying NOT NULL, "chain_id" integer NOT NULL, "date" TIMESTAMP WITH TIME ZONE NOT NULL, "pool_id" character varying NOT NULL, "token_id" character varying NOT NULL, "amount" numeric NOT NULL, "created_at_block_number" integer NOT NULL, "updated_at_block_number" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_25d3dd1398e1a64cd06e31b49e4" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_4c7a8844e42c1008fcfed6a74e" ON "pool_hour_balance" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_451a971d3d8117f1ce4b158ecb" ON "pool_hour_balance" ("token_id") `)
        await db.query(`CREATE TABLE "withdrawal" ("id" character varying NOT NULL, "transaction_id" character varying NOT NULL, "pool_id" character varying NOT NULL, "token_id" character varying NOT NULL, "from" text NOT NULL, "to" text NOT NULL, "origin" text NOT NULL, "amount" numeric NOT NULL, "log_index" integer, "created_at_block_number" integer NOT NULL, "updated_at_block_number" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_840e247aaad3fbd4e18129122a2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_b87670853acbc9551dccde2d10" ON "withdrawal" ("transaction_id") `)
        await db.query(`CREATE INDEX "IDX_1788fb57e581f3de7f0d498733" ON "withdrawal" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_5a58952b2666d1900b1bcf1aee" ON "withdrawal" ("token_id") `)
        await db.query(`CREATE TABLE "tx" ("id" character varying NOT NULL, "gas_used" numeric NOT NULL, "gas_price" numeric NOT NULL, "created_at_block_number" integer NOT NULL, "updated_at_block_number" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_2e04a1db73a003a59dcd4fe916b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "deposit" ("id" character varying NOT NULL, "transaction_id" character varying NOT NULL, "pool_id" character varying NOT NULL, "token_id" character varying NOT NULL, "from" text NOT NULL, "to" text NOT NULL, "origin" text NOT NULL, "amount" numeric NOT NULL, "log_index" integer, "created_at_block_number" integer NOT NULL, "updated_at_block_number" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_6654b4be449dadfd9d03a324b61" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_279d6b292f3b5c23337e4eacd3" ON "deposit" ("transaction_id") `)
        await db.query(`CREATE INDEX "IDX_cf0f9c53f39d72f19478aaaee3" ON "deposit" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_09699258f368ade88316904e54" ON "deposit" ("token_id") `)
        await db.query(`CREATE TABLE "pool" ("id" character varying NOT NULL, "address" text NOT NULL, "chain_id" integer NOT NULL, "pool_factory_id" character varying NOT NULL, "account_id" character varying NOT NULL, "name" text NOT NULL, "description" text NOT NULL, "logo" text NOT NULL, "owner_id" character varying NOT NULL, "created_at_block_number" integer NOT NULL, "updated_at_block_number" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_db1bfe411e1516c01120b85f8fe" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_2126b5e4c6a411b38e9e049b02" ON "pool" ("pool_factory_id") `)
        await db.query(`CREATE INDEX "IDX_7042da86b8de81cc3e9e448f9a" ON "pool" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_6ee0abc520db0e34d73c5bdd3c" ON "pool" ("owner_id") `)
        await db.query(`CREATE TABLE "token_balance" ("id" character varying NOT NULL, "chain_id" integer NOT NULL, "token_id" character varying NOT NULL, "holder_id" character varying NOT NULL, "amount" numeric NOT NULL, "created_at_block_number" integer NOT NULL, "updated_at_block_number" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_dc23ea262a0188977523d90ae7f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_5813c3040e74c285719679c693" ON "token_balance" ("token_id") `)
        await db.query(`CREATE INDEX "IDX_535d618a629db3b5fc75126395" ON "token_balance" ("holder_id") `)
        await db.query(`CREATE TABLE "account" ("id" character varying NOT NULL, "address" text NOT NULL, "account_type" character varying(8) NOT NULL, "created_at_block_number" integer NOT NULL, "updated_at_block_number" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_54115ee388cdb6d86bb4bf5b2ea" PRIMARY KEY ("id"))`)
        await db.query(`ALTER TABLE "pool_factory" ADD CONSTRAINT "FK_37d0c98b2aee82e865df4ca6ed6" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "extension_registry" ADD CONSTRAINT "FK_23035bc1fa4a5b221389e13d92f" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "extension" ADD CONSTRAINT "FK_57ccff353e966f42ce075c9840d" FOREIGN KEY ("extension_registry_id") REFERENCES "extension_registry"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "claim" ADD CONSTRAINT "FK_1be67f374e054c831d78dc04888" FOREIGN KEY ("parent_id") REFERENCES "claim"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "claim" ADD CONSTRAINT "FK_4fa8a234dee5be6b41e76819d25" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "claim" ADD CONSTRAINT "FK_fbd012a2329b07b1687c321385f" FOREIGN KEY ("recipient_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "claim" ADD CONSTRAINT "FK_964f2b34087ff0363398bfcba68" FOREIGN KEY ("state_id") REFERENCES "extension"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "claim" ADD CONSTRAINT "FK_c9c7ae261e98272b62051f3b1ba" FOREIGN KEY ("strategy_id") REFERENCES "extension"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool_day_balance" ADD CONSTRAINT "FK_652bc46dc1f15a99ad2682d0daf" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool_day_balance" ADD CONSTRAINT "FK_7e08123ddf2be25b7888311d8a6" FOREIGN KEY ("token_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool_hour_balance" ADD CONSTRAINT "FK_4c7a8844e42c1008fcfed6a74ef" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool_hour_balance" ADD CONSTRAINT "FK_451a971d3d8117f1ce4b158ecb0" FOREIGN KEY ("token_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "withdrawal" ADD CONSTRAINT "FK_b87670853acbc9551dccde2d103" FOREIGN KEY ("transaction_id") REFERENCES "tx"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "withdrawal" ADD CONSTRAINT "FK_1788fb57e581f3de7f0d4987333" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "withdrawal" ADD CONSTRAINT "FK_5a58952b2666d1900b1bcf1aee0" FOREIGN KEY ("token_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "deposit" ADD CONSTRAINT "FK_279d6b292f3b5c23337e4eacd3a" FOREIGN KEY ("transaction_id") REFERENCES "tx"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "deposit" ADD CONSTRAINT "FK_cf0f9c53f39d72f19478aaaee35" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "deposit" ADD CONSTRAINT "FK_09699258f368ade88316904e54c" FOREIGN KEY ("token_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool" ADD CONSTRAINT "FK_2126b5e4c6a411b38e9e049b021" FOREIGN KEY ("pool_factory_id") REFERENCES "pool_factory"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool" ADD CONSTRAINT "FK_7042da86b8de81cc3e9e448f9a7" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool" ADD CONSTRAINT "FK_6ee0abc520db0e34d73c5bdd3cc" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "token_balance" ADD CONSTRAINT "FK_5813c3040e74c285719679c6935" FOREIGN KEY ("token_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "token_balance" ADD CONSTRAINT "FK_535d618a629db3b5fc751263955" FOREIGN KEY ("holder_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "pool_factory"`)
        await db.query(`DROP INDEX "public"."IDX_37d0c98b2aee82e865df4ca6ed"`)
        await db.query(`DROP TABLE "extension_registry"`)
        await db.query(`DROP INDEX "public"."IDX_23035bc1fa4a5b221389e13d92"`)
        await db.query(`DROP TABLE "extension"`)
        await db.query(`DROP INDEX "public"."IDX_57ccff353e966f42ce075c9840"`)
        await db.query(`DROP TABLE "claim"`)
        await db.query(`DROP INDEX "public"."IDX_1be67f374e054c831d78dc0488"`)
        await db.query(`DROP INDEX "public"."IDX_4fa8a234dee5be6b41e76819d2"`)
        await db.query(`DROP INDEX "public"."IDX_fbd012a2329b07b1687c321385"`)
        await db.query(`DROP INDEX "public"."IDX_964f2b34087ff0363398bfcba6"`)
        await db.query(`DROP INDEX "public"."IDX_c9c7ae261e98272b62051f3b1b"`)
        await db.query(`DROP TABLE "token"`)
        await db.query(`DROP TABLE "pool_day_balance"`)
        await db.query(`DROP INDEX "public"."IDX_652bc46dc1f15a99ad2682d0da"`)
        await db.query(`DROP INDEX "public"."IDX_7e08123ddf2be25b7888311d8a"`)
        await db.query(`DROP TABLE "pool_hour_balance"`)
        await db.query(`DROP INDEX "public"."IDX_4c7a8844e42c1008fcfed6a74e"`)
        await db.query(`DROP INDEX "public"."IDX_451a971d3d8117f1ce4b158ecb"`)
        await db.query(`DROP TABLE "withdrawal"`)
        await db.query(`DROP INDEX "public"."IDX_b87670853acbc9551dccde2d10"`)
        await db.query(`DROP INDEX "public"."IDX_1788fb57e581f3de7f0d498733"`)
        await db.query(`DROP INDEX "public"."IDX_5a58952b2666d1900b1bcf1aee"`)
        await db.query(`DROP TABLE "tx"`)
        await db.query(`DROP TABLE "deposit"`)
        await db.query(`DROP INDEX "public"."IDX_279d6b292f3b5c23337e4eacd3"`)
        await db.query(`DROP INDEX "public"."IDX_cf0f9c53f39d72f19478aaaee3"`)
        await db.query(`DROP INDEX "public"."IDX_09699258f368ade88316904e54"`)
        await db.query(`DROP TABLE "pool"`)
        await db.query(`DROP INDEX "public"."IDX_2126b5e4c6a411b38e9e049b02"`)
        await db.query(`DROP INDEX "public"."IDX_7042da86b8de81cc3e9e448f9a"`)
        await db.query(`DROP INDEX "public"."IDX_6ee0abc520db0e34d73c5bdd3c"`)
        await db.query(`DROP TABLE "token_balance"`)
        await db.query(`DROP INDEX "public"."IDX_5813c3040e74c285719679c693"`)
        await db.query(`DROP INDEX "public"."IDX_535d618a629db3b5fc75126395"`)
        await db.query(`DROP TABLE "account"`)
        await db.query(`ALTER TABLE "pool_factory" DROP CONSTRAINT "FK_37d0c98b2aee82e865df4ca6ed6"`)
        await db.query(`ALTER TABLE "extension_registry" DROP CONSTRAINT "FK_23035bc1fa4a5b221389e13d92f"`)
        await db.query(`ALTER TABLE "extension" DROP CONSTRAINT "FK_57ccff353e966f42ce075c9840d"`)
        await db.query(`ALTER TABLE "claim" DROP CONSTRAINT "FK_1be67f374e054c831d78dc04888"`)
        await db.query(`ALTER TABLE "claim" DROP CONSTRAINT "FK_4fa8a234dee5be6b41e76819d25"`)
        await db.query(`ALTER TABLE "claim" DROP CONSTRAINT "FK_fbd012a2329b07b1687c321385f"`)
        await db.query(`ALTER TABLE "claim" DROP CONSTRAINT "FK_964f2b34087ff0363398bfcba68"`)
        await db.query(`ALTER TABLE "claim" DROP CONSTRAINT "FK_c9c7ae261e98272b62051f3b1ba"`)
        await db.query(`ALTER TABLE "pool_day_balance" DROP CONSTRAINT "FK_652bc46dc1f15a99ad2682d0daf"`)
        await db.query(`ALTER TABLE "pool_day_balance" DROP CONSTRAINT "FK_7e08123ddf2be25b7888311d8a6"`)
        await db.query(`ALTER TABLE "pool_hour_balance" DROP CONSTRAINT "FK_4c7a8844e42c1008fcfed6a74ef"`)
        await db.query(`ALTER TABLE "pool_hour_balance" DROP CONSTRAINT "FK_451a971d3d8117f1ce4b158ecb0"`)
        await db.query(`ALTER TABLE "withdrawal" DROP CONSTRAINT "FK_b87670853acbc9551dccde2d103"`)
        await db.query(`ALTER TABLE "withdrawal" DROP CONSTRAINT "FK_1788fb57e581f3de7f0d4987333"`)
        await db.query(`ALTER TABLE "withdrawal" DROP CONSTRAINT "FK_5a58952b2666d1900b1bcf1aee0"`)
        await db.query(`ALTER TABLE "deposit" DROP CONSTRAINT "FK_279d6b292f3b5c23337e4eacd3a"`)
        await db.query(`ALTER TABLE "deposit" DROP CONSTRAINT "FK_cf0f9c53f39d72f19478aaaee35"`)
        await db.query(`ALTER TABLE "deposit" DROP CONSTRAINT "FK_09699258f368ade88316904e54c"`)
        await db.query(`ALTER TABLE "pool" DROP CONSTRAINT "FK_2126b5e4c6a411b38e9e049b021"`)
        await db.query(`ALTER TABLE "pool" DROP CONSTRAINT "FK_7042da86b8de81cc3e9e448f9a7"`)
        await db.query(`ALTER TABLE "pool" DROP CONSTRAINT "FK_6ee0abc520db0e34d73c5bdd3cc"`)
        await db.query(`ALTER TABLE "token_balance" DROP CONSTRAINT "FK_5813c3040e74c285719679c6935"`)
        await db.query(`ALTER TABLE "token_balance" DROP CONSTRAINT "FK_535d618a629db3b5fc751263955"`)
    }
}
